"""add_description_and_verified_by_user_id

Revision ID: 8e03e9ddf3a9
Revises: c1e1b3291bf0
Create Date: 2026-05-20 22:20:21.085686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e03e9ddf3a9'
down_revision = 'c1e1b3291bf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=120),
               nullable=False)
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('verification_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))
        batch_op.create_index(batch_op.f('ix_verification_history_verified_by_user_id'), ['verified_by_user_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['verified_by_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_verification_history_verified_by_user_id'))
        batch_op.drop_column('description')
        batch_op.drop_column('verified_by_user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=120),
               nullable=True)

    # ### end Alembic commands ###
